### ISSUE TITLE
Change visual design of hard-wrap setting?

### ISSUE THREAD

**Issue by davelab6** [vikagrabowska/Octopus#5]
Similar to #4, in https://github.com/googlefonts/roboto-flex/issues/403 there was confusion on the hard-wrap setting being an axis of that name, not a different kind of property than the axes settings. Maybe a color, different shape, etc could help to differentiate it?

**Comment by vikagrabowska** [comment]
I've just pushed V.0.95.2 where hard-wrap setting has white background to distinct it better from axis settings.
